### PR TITLE
Correct undefined variable error

### PR DESCRIPTION
**Pull request by johnrobertwilson**

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @johnrobertwilson,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by johnrobertwilson** [comment]
I’ve signed the CLA, thank you

**Comment by amiras89** [comment]
@johnrobertwilson please push pr to client-generator next time as written here:
https://github.com/kaltura/KalturaGeneratedAPIClientsNodeJS#code-contributions

Due to urgency, made it on your behalf
Thanks !
https://github.com/kaltura/clients-generator/pull/575

**Comment by jessp01** [comment]
Hi @johnrobertwilson ,

As noted in the comment by @amiras89 - this was corrected here https://github.com/kaltura/clients-generator/commit/c7a0bb0b6fdf1c26db658e78ce280e49b7c1d04f#diff-a7abd796c4eacbce5de2c339bde4ce5db9df51ccfab02a398dd9dce5bd18d7f5
Closing this pull.

Thanks,

**Pull request closed without merging**
